version: '3.7'

services:
  # Base de données PostgreSQL
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: atelier_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - atelier_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend FastAPI
  backend:
    build: ./back-fastapi
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/atelier_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - atelier_network

  # Frontend React avec Vite
  frontend:
    build: ./vite-project
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - atelier_network

volumes:
  postgres_data:

networks:
  atelier_network:
    driver: bridge